### ISSUE TITLE
Clicking Extension Does Not Enable/Disable Extension

### ISSUE THREAD

**Issue by tristinDLC** [elrumo/stackOverflow_focus#1]
When selecting the option to only enable the extension when being clicked on, it only brings up the extension info panel and does not toggle the extension. See attached image to show that I have it set to be clickable, but nothing happens. 

![Screen Shot 2020-07-17 at 12 04 03 AM](https://user-images.githubusercontent.com/24608720/87758409-45b00300-c7c1-11ea-82bc-fc1eb25b75ff.png)

macOS 10.15.5
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by elrumo** [comment]
Good shout, I'll update it so you can disable/enable it from the popup. Also, the extension is now on the Chrome store, which I'll also update once I get the popup fully working.

**Comment by elrumo** [comment]
You should now have the ability to temporarily turn off the plugin.

**Comment by tristinDLC** [comment]
I'm sorry for the huge delay in getting back to you, especially when you provided a fix so quickly... but the updated extension has been installed and it works great now. Thanks for the effort!
