### ISSUE TITLE
Option to disable shadow

### ISSUE THREAD

**Issue by Armaldio** [elrumo/stackOverflow_focus#2]
On Dark theme or just because it's a matter of taste, add ability to remove the shadow

![image](https://user-images.githubusercontent.com/3089715/93062394-2b858a80-f675-11ea-8dab-8912581759fc.png)

![image](https://user-images.githubusercontent.com/3089715/93062461-3dffc400-f675-11ea-9744-2a2cdc8f2085.png)

**Comment by elrumo** [comment]
Good shout, that shouldn't take too hard to implement. 

While I'm at it, what do you think of making the background colour the same as the StackOverflow colour? So it feels like there's no frame around it.

**Comment by Armaldio** [comment]
Sure you can add that as an option too ;)
Great work anyway 👍 

Also, for reference, I was using these two Stylish themes before this extension: 
![image](https://user-images.githubusercontent.com/3089715/93080909-b757e080-f68e-11ea-9443-bae5adef1663.png)

**Comment by elrumo** [comment]
Awesome! Thanks, I'll have a look at those. 

Also, unrelated to the issue, but if you haven't already could you upvote it on ProductHunt (or even share the link on Twitter)?

[https://www.producthunt.com/posts/stackoverflow-focus](https://www.producthunt.com/posts/stackoverflow-focus)

**Comment by elrumo** [comment]
I've updated the plugin and now has some more options, including disabling the drop shadow.
