### ISSUE TITLE
Support ru.stackoverflow.com?

### ISSUE THREAD

**Issue by deevroman** [elrumo/stackOverflow_focus#5]
Will there be support for Russian Stackoverflow?

**Comment by elrumo** [comment]
Thanks for the feedback, I've not added support for any localised Satckoverflow, so it works with ru.stackoverflow.com and any **.stackoverflow.com. I'll update it shortly.

**Comment by elrumo** [comment]
The new update is on the [Chrome store](https://chrome.google.com/webstore/detail/stackoverflow-focus/gaeipjkcdkpbfdfmakonllgiboaonopp?hl=en-GB&authuser=0)
